name: Backup Repository

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Ensure branch and commit exist
        run: |
          if [ -z "$(git rev-parse --branches)" ]; then
            echo "Creating initial commit"
            echo "Initial commit" > README.md
            git add README.md
            git commit -m "Initial commit"
          fi
          git branch -M master

      
      - name: Push to target repository
        env:
          TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
        run: |
          git remote add backup https://${{ secrets.TARGET_REPO_TOKEN }}@github.com/moanxxx/test_workflou11.git
          git push -u backup master
